Latest HydraDX / Basilisk
polkawallet-io/bridge pull request #69
Opened 2023-06-15 11:14 UTC by nohaapav

Hi guys, i've fixed some HydraDX & Basilisk stuff regarding v3, also added new adapters .. Feel free to merge

2023-06-20 08:25 UTC, nohaapav commented
Guys removed dest weight from hydradx route config again, we went to v3 yesterdy
https://github.com/polkawallet-io/bridge/pull/69/commits/6b33c9ad791cdb1d18e148a1709b68444fdbd277

2023-06-20 09:32 UTC, RomeroYang commented on src/adapters/hydradx.ts
> +    token: "aUSD",
No need here either.

2023-06-20 09:34 UTC, RomeroYang commented on src/adapters/hydradx.ts
> +  aUSD: {
No need here either.

2023-06-20 09:38 UTC, RomeroYang commented on src/configs/chains/kusama-chains.ts
> +    icon: "",
It's better to provide an icon source, you may add the icon into resouces.acala.network through this repo: https://github.com/open-web3-stack/token-resources

2023-06-20 09:41 UTC, RomeroYang requested changes
1. remove unused token aUSD in Karura, and use KUSD instead.
2. provide an network icon for tinkernet (optional)

2023-06-22 23:07 UTC, tien commented
Awesome stuff @nohaapav & @RomeroYang, can't wait for this to get merged 💪

2023-06-30 10:31 UTC, nohaapav commented on src/adapters/hydradx.ts
> +  aUSD: {
Done

2023-06-30 10:32 UTC, nohaapav commented on src/adapters/acala/karura-configs.ts
> +    token: "aUSD",
Done

2023-06-30 11:29 UTC, nohaapav commented
@RomeroYang @tien Guys btw fixed interlay (they went to v3 21st of June), also aUSD has been removed. Plus additional centrifuge route was added for hydradx. ;) So just tinkernet icon is missing but i guess not a blocker atm ..

2023-07-03 02:04 UTC, RomeroYang approved these changes

2023-07-03 02:08 UTC, merged